### ISSUE TITLE
Write a device tree overlay for D-pad input

### ISSUE THREAD

**Issue by zjcers** [EECS581Team15/WifiLMR#13]
The Linux kernel has a nice driver for mapping raw GPIOs into a keyboard-like device: https://www.kernel.org/doc/Documentation/devicetree/bindings/input/gpio-keys.txt. Our D-pad will have 5 inputs: KEY_UP, KEY_DOWN, KEY_LEFT, KEY_RIGHT, KEY_ENTER. These have pretty obvious mappings to normal Linux keys. There's also built-in debouncing, so we don't need to implement that either.

**Comment by jackdweber** [comment]
http://blog.gegg.us/2017/01/setting-up-a-gpio-button-keyboard-on-a-raspberry-pi/

Obviously blocked until we have the device.

**Comment by zjcers** [comment]
I've got this all but done in a local branch.
