### ISSUE TITLE
UI design

### ISSUE THREAD

**Issue by zjcers** [EECS581Team15/WifiLMR#2]
* Create mock ups for the various user interface screens.
   Make some pictures in Photoshop or GIMP as reference for when we're implementing the UI.
* Document user work flows
   Diagrams for how a user uses the UI (ex: for this task, press <button> to reach this screen, or select the given menu item)

**Comment by zjcers** [comment]
The mocks can just be attached to this ticket.

**Comment by jackdweber** [comment]
UI Designs needed
* Main Screen
* Settings / Applications screen
    * Possible theming 
    * WiFi Selection?
    * Volumes
    * More to come
* Channel selection
* Messaging Screen
    * Messaging Detail Screen

**Comment by zjcers** [comment]
Volume and channel selection will have hardware controls. We'll probably want a selection screen for channels either way, though. Might want a nice display slider to pop up when adjusting volume, too.

I think "zones" (groups of channels) were in the spec, so we'll probably want a list screen for that, too.

**Comment by zjcers** [comment]
Note: the screen we selected has a resolution of 160x128.

**Comment by AstralA** [comment]
![main screen](https://user-images.githubusercontent.com/13712591/47684361-a1c39580-dba0-11e8-9bed-2f1fad8e6d8f.png) Main Screen
![setting screen](https://user-images.githubusercontent.com/13712591/47684363-a1c39580-dba0-11e8-9bc9-a07e5d21c3de.png) Setting Screen
![channel screen](https://user-images.githubusercontent.com/13712591/47684360-a12aff00-dba0-11e8-8a29-942b50405088.png) Channel Screen
![messages screen](https://user-images.githubusercontent.com/13712591/47684362-a1c39580-dba0-11e8-97ea-b817603038be.png) Messages Screen
![zones screen](https://user-images.githubusercontent.com/13712591/47684366-a25c2c00-dba0-11e8-8aa5-c879c2f5b016.png) Zones Screen
![user workflow](https://user-images.githubusercontent.com/13712591/47684365-a1c39580-dba0-11e8-9cee-78f1c66c8879.png) User Workflow
