### ISSUE TITLE
UI Design Resources

### ISSUE THREAD

**Issue by jackdweber** [EECS581Team15/WifiLMR#25]
Amrit please upload the resources for the UI. I.E. Back button, battery, wifi symbol bitmaps. Etc.

**Comment by AstralA** [comment]
![volume icon](https://user-images.githubusercontent.com/13712591/47751494-e3674580-dc5f-11e8-8408-4d3e47d552f2.png)
![wifi icon](https://user-images.githubusercontent.com/13712591/47751495-e3ffdc00-dc5f-11e8-9d86-1364f9581807.png)
![back icon](https://user-images.githubusercontent.com/13712591/47751496-e3ffdc00-dc5f-11e8-9bf3-4c2e8eaf726d.png)
![battery icon](https://user-images.githubusercontent.com/13712591/47751497-e3ffdc00-dc5f-11e8-9a05-84113250c3bd.png)
![message icon](https://user-images.githubusercontent.com/13712591/47751498-e3ffdc00-dc5f-11e8-96a4-ff7efa76a139.png)
![radio icon](https://user-images.githubusercontent.com/13712591/47751499-e3ffdc00-dc5f-11e8-9db5-b57c5131a0d3.png)
![scroll icon](https://user-images.githubusercontent.com/13712591/47751500-e4987280-dc5f-11e8-844e-98fa989f9e69.png)
![setting icon](https://user-images.githubusercontent.com/13712591/47751501-e4987280-dc5f-11e8-8937-d40bc3b06a75.png)
