### ISSUE TITLE
UI MVP

### ISSUE THREAD

**Issue by zjcers** [EECS581Team15/WifiLMR#3]
Implementation of the UI from #2. The implementation definitely needs to run on ARM GNU/Linux, but it would be really nice if the chosen toolkit library supports multiple platforms. It also needs to be .NET Core compatible because of our implementation choices. From these constraints, I recommend GTK#. It runs on Linux, Windows, and OS X (I believe). There's also a lot of examples for it. The only problem that see is that it rather heavy, but no more so than Qt.

**Comment by zjcers** [comment]
@johnying7 You might want to look at this.

**Comment by jackdweber** [comment]
see branch initial_ui
