### ISSUE TITLE
Battery gauge should be an icon

### ISSUE THREAD

**Issue by zjcers** [EECS581Team15/WifiLMR#50]
The battery meter should be an icon that "fills up" with charge, like on most phones/portable devices.  Extra points if it changes color at certain percentages (say, red at < 20%, orange at < 40%, green otherwise).

**Comment by zjcers** [comment]
Since tkinter makes it hard to draw redraw graphics, how about an outlined rectangle with a colored background (which turns red on low battery) with the percentage text centered inside of it?

**Comment by AstralA** [comment]
Yes, I'm trying to build it that way.
